/*
 *
 *  Copyright (C) 2019-2026, OFFIS e.V.
 *  All rights reserved.  See COPYRIGHT file for details.
 *
 *  This software and supporting documentation were developed by
 *
 *    OFFIS e.V.
 *    R&D Division Health
 *    Escherweg 2
 *    D-26121 Oldenburg, Germany
 *
 *
 *  Module:  dcmtls
 *
 *  Authors:  Michel Amat, Damien Lerat
 *
 *  Purpose: TLS test for classes DcmSCP and DcmSCPPool
 *
 *  Note: This test will fail after 2029-02-25 due to certificate expiry.
 *        The keys embedded in this file should be replaced then (see below).
 *
 */

#include "dcmtk/config/osconfig.h"    /* make sure OS specific configuration is included first */

#include "dcmtk/ofstd/oftest.h"
#include "dcmtk/ofstd/oftimer.h"
#include "dcmtk/ofstd/ofrand.h"
#include "dcmtk/oflog/consap.h"
#include "dcmtk/dcmnet/scp.h"
#include "dcmtk/dcmnet/scu.h"
#include "dcmtk/dcmnet/scppool.h"
#include "dcmtk/dcmnet/dcmlayer.h"
#include "dcmtk/dcmtls/tlsscu.h"
#include <cmath>

#ifdef WITH_THREADS
#ifdef WITH_OPENSSL

#define BAILOUT(msg) do { \
    OFCHECK_FAIL(msg); \
    return; \
} while (0)

const size_t NUM_THREADS = 20;

/** TestSCP derived from DcmSCP in order to test TLS functionality
 *  through function setTransportLayer of DcmSCPConfig.
 *
 *  Additionally the SCP derives from OFThread in order to construct the
 *  test case (i.e. send data with SCU at the same time and check results).
 */
struct TestSCP: DcmSCP, OFThread
{
    /** Constructor
     */
    TestSCP() :
        DcmSCP(),
        m_listen_result(EC_NotYetImplemented), // value indicating "not set"
        m_set_stop_after_assoc(OFFalse),
        m_set_stop_after_timeout(OFFalse),
        m_is_running(OFFalse)
    {
    }

    /** Clear settings
     */
    void clear()
    {
        m_listen_result = EC_NotYetImplemented;
        m_set_stop_after_assoc = OFFalse;
        m_set_stop_after_timeout = OFFalse;
        m_is_running = OFFalse;
    }

    /** Overwrite method from DcmSCP in order to test feature to stop after current
     *  association.
     *  @return Returns value of m_set_stop_after_assoc
     */
    virtual OFBool stopAfterCurrentAssociation()
    {
        return m_set_stop_after_assoc;
    }

    /** Overwrite method from DcmSCP in order to test feature to stop after
    *   the SCP's connection timeout occurred in non-blocking mode.
    *   @return Returns value of m_set_stop_after_timeout
    */
    virtual OFBool stopAfterConnectionTimeout()
    {
        return m_set_stop_after_timeout;
    }

    /// The result returned my SCP's listen() method
    OFCondition m_listen_result;
    /// If set, the SCP should stop after the currently running association
    OFBool m_set_stop_after_assoc;
    /// If set, the SCP should stop after TCP timeout occurred in non-blocking mode
    OFBool m_set_stop_after_timeout;
    /// indicates whether the thread is currently running
    volatile OFBool m_is_running;

    /** Method called by OFThread to start SCP operation. Starts listen() loop of DcmSCP.
    */
    virtual void run()
    {
        m_is_running = OFTrue;
        m_listen_result = listen();
        m_is_running = OFFalse;
    }

};

// -------------- End of class TestSCP -------------------------

struct TestPool : DcmSCPPool<>, OFThread
{
    OFCondition m_listen_result;
    volatile OFBool m_is_running;

    TestPool()
    : DcmSCPPool<>()
    , OFThread()
    , m_listen_result(EC_NotYetImplemented)
    , m_is_running(OFFalse)
    { }

protected:
    void run()
    {
        m_is_running = OFTrue;
        m_listen_result = listen();
        m_is_running = OFFalse;
        DCMNET_DEBUG("TestPool: SCP Pool thread stopped, listen() returned: " << m_listen_result.text());
    }
};

// -------------- End of class TestPool -------------------------

struct TestTLSSCU : DcmTLSSCU, OFThread
{
    OFCondition result;
protected:
    void run()
    {
        OFCHECK(negotiateAssociation().good());
        result = sendECHORequest(0);
        releaseAssociation();
    }
};

// -------------- End of class TestTLSSCU -------------------------


#define PRIVATE_KEY_FILENAME "privkey.pem"
#define PUBLIC_SELFSIGNED_CERT_FILENAME "pubselfsignedcert.pem"


/** Method write_temp_key_cert_files writes private key and public certificate files,
 *  needed by tests dcmtls_scp_tls and dcmtls_scp_pool_tls.
 *  It corresponds to the files generated by the following openssl command>
 *  > openssl req -x509 -newkey rsa:4096 -noenc -keyout PRIVATE_KEY_FILENAME
 *    -out PUBLIC_SELFSIGNED_CERT_FILENAME -days 3653 -subj "/C=DE/ST=DcmTls/L=Tests/O=OFFIS/OU=DCMTK/CN=dicom@offis.de"
 *  The private key is stored UNENCRYPTED on purpose. Loading an encrypted PKCS#8
 *  key relies on the OpenSSL build providing a decoder that can decrypt it, and
 *  some installations (observed with a custom OpenSSL 3.5 build) fail this with
 *  "DECODER routines::unsupported", regardless of the cipher used. An unencrypted
 *  key needs no decryption and loads on any provider configuration; this test
 *  exercises TLS communication, not encrypted-key loading.
 *  @note The certificate will expire on 2029-02-25. The keys should be replaced then.
 */
void write_temp_key_cert_files()
{
    const char * privKey="-----BEGIN PRIVATE KEY-----\n"
"MIIJQQIBADANBgkqhkiG9w0BAQEFAASCCSswggknAgEAAoICAQC+YYUnYLhLIuhi\n"
"zqUUO4KtzaKmqJ4zY5mn9H9J0U721C932F702CX38KhZOMRc/7C0cNxdYWDFS7iE\n"
"jl90kwNmfkdVK8XjdLQ6GVTjvkVI6caeQBe3MgSvVRtczmhMqgP8DoNFSP7/OUTT\n"
"cTcoHquoVIrViCOH8vc/6mfBFA5qsoGDwi3A/LgUh/mNHqAZqAkomEzmHihNrM9R\n"
"A8a+7doqjNf7IrQUHx7ubK+RozprXvqMTKGddy+gbbmFzCyWLgDC2ak25p1qMNVq\n"
"DlZYhrfV+Q0M7fQGOJw97SLjyHXT9P93IWO+WbLCdSmj/GBIx/nLMzRSVUbPPvUm\n"
"37uhy2mSfgIhE8w8ybVnXRLJdxUyHwpZVm+UktCPv/IU8LdgxA1sKx7+S/7BgwIS\n"
"0rXX3O3yeB1z/dFSkT44Ju+Ze8MAPxVoyWbF+SaKmy9LcsRpjjIusJLTDT3W1Pw+\n"
"AymYDt0BKq5rDnd4gx/dKuRd/921GFAnrZE86rmWbvTuqYGCYeaJfRnhCDmjWLgq\n"
"/jlrc37fTv2TJXF7TGNjkfGsjS1StC9IOnGXyhV0klvK5xxPvIGVHUbVi2bXDW9H\n"
"UTmtZ6O0vFM7NgRhUimndmrLbEJJGNGG36h5kIMe5xo7C99utu+d077itL4ZPcOy\n"
"eeEHXaObjxQEzQ8xRnkDOWzIDTU9ZQIDAQABAoICAGOgtQW+X7MyOVo7ube0zNYX\n"
"Xp7IbsGFxctW76W5mxEgSRb2a/rFglkV34ORaXEhfV9wEGHtq66TyaPUva9Ln+Pr\n"
"AXlYxt4ZHJeq2fm0gJ1/eSkncUG1My5t4zvV6E72Sc+F6LxBTvBRD+t2u96K7lnQ\n"
"pDbKX42tYCZajKFF1aWQdKZ232q21b4oyjdHZ5EFloVf7h4eegjr/jHvP/p6jkjm\n"
"G8CYkJRXFODAj8AvI0s9EPCKyaiVzp6tzQBvsIWG3W8aaKsKVCZWF9jAV/9LwLiA\n"
"9ItnmuQGi/z8M93v8XlSJL47Au+CEUIh/gCK+fgcbmQgD6lmZv/den01aANrZ3sR\n"
"hgwsv6eTmtotZdskW5pA5rnJBtcZ1x5kHp1hQ4dHBNcfzy+NKMouMfQBLPn21ock\n"
"bMN+Tr9tmF60+bjrGQ0z0b/jzCaE3LwC2maeE81D0wtnpdqstyxJj0LM7f6fFpIp\n"
"r0FbxBXFefyuEE1L9SmV9vUbP+Ps37l5CIWtRSHE/0KR4/fXDIJfe94+UCCAffgV\n"
"o8UMQLhxiU03Gh9HHlNdY7CK7niSvUjB0mMICgVOkD3LFTLpUW9sFSi5LhIrEqAi\n"
"RZIwdMlJ6xfMTkWRIPICHQpljqJktU0/4mFoienJBAm16wHHDckf3l3op80S1BqP\n"
"URNPAJDeS9NR4ZflO/sBAoIBAQD1m8ewVfHsxJsqkjaODL+w3d9RECY+u1u9XXcb\n"
"AStAt3xnX0L03hGq7KQz741/1VsHHuHI2E56pOfj+VX+88542k/112JaIvxwdhEf\n"
"sm10MVm0v8YmJe6lmpnjUE3JFCHlzvcWL/S+tFJUV3h3mgFg2dNK8stGIMm8HUYR\n"
"THlw0D3FrfCXrlF2AT5bkwHakaAInGIhY28HSDriBJvTpXZvl0CMk9f2UxOmUVer\n"
"RZPcdHgTok6x1ZCwtVpW4bmEkVYP7UqVvxb3d6nbkrx6bA7yrAMlZe0RIxNvjTUO\n"
"Ma2WUu+LsVTY9lGy27dI2OJrnm8cIBd0ix+7aizrWKAN5BgNAoIBAQDGb5AB28a/\n"
"iuFGYyFQpgvdiSKKLNne7zjxOcc379STbZkF7R7LNj/EDFbFOVayPx+Cwq1awX9e\n"
"QkaqzcrTj6etCexqnCak5sQXzjyXEWwhZ9jJDpHAFd6BdrAn2D+a9bWGqy3mrrEF\n"
"F/v/mO8dWwJl8lXr3gwIDjZjpRbYf+zcD0CpGdFOLOYwW5OkogCc8GhkU/lrrYNE\n"
"E/FT+B/xYewvKcBFErDUX1gmidi7Wm0bMBL7DL7BK9AVoXdZ1meqqiR5W9CS16PR\n"
"US3cAgY7DxzOT/BFVFgpcmwq0b8G+DPCVm9i8wryanFkCQU7JAxh+lMtxnbPYV/1\n"
"QbPdxu5SLEy5AoIBABsnxCZc+kihXD6St/Fwu2kEvwIpdPEOqg//24Fi2bNoFhsf\n"
"zzlfrDhnvaf4Xn65yjy5T2FzeQnaXcE4+iccMcHu8VRPIhKxN5P/mdkVU0C7jB2N\n"
"7oydOQuaUlVttYv769uKzIrpdnf3W/rzSOCAaJKawt/QhGUWjvd7jRmwiOTOQWYv\n"
"2yAKJ/uSG6DoWhYeb8FD+R2T7tyxQcFnnQsDilrAMGTam9AiU1PaPoUzRivjvLr/\n"
"ARBsenjvNDPS9T4RC6DrLYns/M8TrfYW/TvT4rs2BYsG//UbGbUFuc399CFgvheF\n"
"3cm3QkUyQcuOH0qi08oaSj2afEGudZT30Yp3o6kCggEAfIkDjccKYqecXfpUrDKp\n"
"e61W+fTP/zOPPwUN3DMt7CB6StfX3Zz8Q+OiiUBFArTO59eZyD1r3BIoG4Xv5vpf\n"
"Nx/lObsqHY+ePXp3WC/c9tIfoX79RdnzvLhqMXdr46qU9CF2OzIjcpjs1Cp81qWJ\n"
"ScXe2pqOXnfc9ohjYBhY5HrGD9peG3veMzcl38q0K8pNGboB7OwGV7FUYWh1U54r\n"
"BiZjvnXOeFomDnmwhVRo6QkwwFHtXXpLq2ecacs/YEJLhcZzjdS7wN/7sfmrQ2Fm\n"
"qKxOlJQsiEaBUBY2lv8qLKrmWOlDU4QuCaQHnmgvRUY+8Zl+cwQfnuJPKb5xTyzy\n"
"MQKCAQA3AfvNnoW7uWNwwC5/s2Jt3DjC0ZANDI/UePKIV/3Mlv8u0xVb1orvogLt\n"
"lc/60dDOCo48BzdtOfAehqExNu1P5q7JBaVI6HuNtfPOAgC+fsE2URU8//JF64fB\n"
"P4BW596o5RlqKnDwiSEsl5UEpIjlN0ENSwS8Fb0U1y+W/wEU/v0NskBZBI0tP//G\n"
"3/zU9UDRXEWKiY6OTpAa1rZGbKQ5HY6YdMwCaW2dr8Z0F2gFky/BwR5qZGCXaZ9D\n"
"eJGSEl2DBbLAsSaXoh+Dmmhj+kTjePzQb1N7Eo6hbPTc+eD0QKbxFNR89A4a3viT\n"
"YJmMv8AsBGzNCNOwab/4VogCIkt1\n"
"-----END PRIVATE KEY-----";
    const size_t lenPrivKey = 3267;
    FILE *privKeyFile = fopen(PRIVATE_KEY_FILENAME, "wb");
    OFCHECK(privKeyFile);
    OFCHECK(lenPrivKey == fwrite(privKey, 1, lenPrivKey, privKeyFile));
    fclose(privKeyFile);

    const char* pubSelfSIgnedCert =
    "-----BEGIN CERTIFICATE-----\n"
"MIIFpDCCA4ygAwIBAgIJAJRhU6soYQspMA0GCSqGSIb3DQEBCwUAMGcxCzAJBgNV\n"
"BAYTAkRFMQ8wDQYDVQQIDAZEY21UbHMxDjAMBgNVBAcMBVRlc3RzMQ4wDAYDVQQK\n"
"DAVPRkZJUzEOMAwGA1UECwwFRENNVEsxFzAVBgNVBAMMDmRpY29tQG9mZmlzLmRl\n"
"MB4XDTE5MDIyNTE0MjY0NVoXDTI5MDIyNTE0MjY0NVowZzELMAkGA1UEBhMCREUx\n"
"DzANBgNVBAgMBkRjbVRsczEOMAwGA1UEBwwFVGVzdHMxDjAMBgNVBAoMBU9GRklT\n"
"MQ4wDAYDVQQLDAVEQ01USzEXMBUGA1UEAwwOZGljb21Ab2ZmaXMuZGUwggIiMA0G\n"
"CSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQC+YYUnYLhLIuhizqUUO4KtzaKmqJ4z\n"
"Y5mn9H9J0U721C932F702CX38KhZOMRc/7C0cNxdYWDFS7iEjl90kwNmfkdVK8Xj\n"
"dLQ6GVTjvkVI6caeQBe3MgSvVRtczmhMqgP8DoNFSP7/OUTTcTcoHquoVIrViCOH\n"
"8vc/6mfBFA5qsoGDwi3A/LgUh/mNHqAZqAkomEzmHihNrM9RA8a+7doqjNf7IrQU\n"
"Hx7ubK+RozprXvqMTKGddy+gbbmFzCyWLgDC2ak25p1qMNVqDlZYhrfV+Q0M7fQG\n"
"OJw97SLjyHXT9P93IWO+WbLCdSmj/GBIx/nLMzRSVUbPPvUm37uhy2mSfgIhE8w8\n"
"ybVnXRLJdxUyHwpZVm+UktCPv/IU8LdgxA1sKx7+S/7BgwIS0rXX3O3yeB1z/dFS\n"
"kT44Ju+Ze8MAPxVoyWbF+SaKmy9LcsRpjjIusJLTDT3W1Pw+AymYDt0BKq5rDnd4\n"
"gx/dKuRd/921GFAnrZE86rmWbvTuqYGCYeaJfRnhCDmjWLgq/jlrc37fTv2TJXF7\n"
"TGNjkfGsjS1StC9IOnGXyhV0klvK5xxPvIGVHUbVi2bXDW9HUTmtZ6O0vFM7NgRh\n"
"UimndmrLbEJJGNGG36h5kIMe5xo7C99utu+d077itL4ZPcOyeeEHXaObjxQEzQ8x\n"
"RnkDOWzIDTU9ZQIDAQABo1MwUTAdBgNVHQ4EFgQU84HK6/XZJXpkS53bNQSma5YR\n"
"QIUwHwYDVR0jBBgwFoAU84HK6/XZJXpkS53bNQSma5YRQIUwDwYDVR0TAQH/BAUw\n"
"AwEB/zANBgkqhkiG9w0BAQsFAAOCAgEAdNRVhkbUS77PlG6TvwYBhRwijy0F3rUX\n"
"BVs4MidSaK8V9Cxa/m018GV0xoz52zIibLUiKLvRUNo3qS24Gbfbh9fdKoIBaTpG\n"
"ike3lS19ddovqQE6WsTTQWjbVP5+B4BVvGbqJNBUFI1vn8dxHFCmWDWqQJy44PqF\n"
"bp88vegFc51dTsrWVWfvTVUP56vmINm2EnvCHEJjQXp7AODlvanC358oJ18YWHzX\n"
"WgGqTE7J4Eab9lmRWMb+ArHvVqwXm5aIFAl/JJ3faJIgW1pqGyKnlQYeiQOOy+YG\n"
"pXCqUxiTMyWP27hoCMG5v3IXdbmIXedD6CwAV0yq6uZUz62g23rXaJiG0wILWMP0\n"
"xzPGnBJHz7VmXMPX1Fs8AxgHZn41N1LCT1BmnFMPmTQb4v/eHSihYHVORkvhdwQu\n"
"LJxKz8oawnka6n9UXF+rVdJjXCeYEA5Y9ThW6Qio3vjrFR5vX70EuVlu/bXqSg3J\n"
"tw+7Gn0C1XfjBtnRJPcSKdBhrkooB2Kl6nkgxy1yTyOXvG1xLeJgJw6/MiCuFu5g\n"
"DZRABWjQPrqv8rFyYm7jwa8sTAppmANazi6SsUGC27cXICVGw3zP7FrXI3jerMkv\n"
"LN+tQ/fnbPFx0kM8PW8Fx6/ns51MMzDZkCdD8yM/Bg74culg20rr25MAa/L0VGq8\n"
"x+yqEeQzzYQ=\n"
"-----END CERTIFICATE-----";
    const size_t lenPubSelfSignedCert = 2016;
    FILE *pubSelfSignedCertFile = fopen(PUBLIC_SELFSIGNED_CERT_FILENAME, "wb");
    OFCHECK(pubSelfSignedCertFile);
    OFCHECK(lenPubSelfSignedCert == fwrite(pubSelfSIgnedCert, 1, lenPubSelfSignedCert, pubSelfSignedCertFile));
    fclose(pubSelfSignedCertFile);
}

// Function for initialization of logs with console appender
void initLogs()
{
    const char * const LOG_PATTERN_LAYOUT = "%D{%Y-%m-%d %H:%M:%S.%q} %5p: %m%n";
    OFunique_ptr < dcmtk::log4cplus::Layout > layout(new dcmtk::log4cplus::PatternLayout(LOG_PATTERN_LAYOUT));
    dcmtk::log4cplus::SharedAppenderPtr console(new dcmtk::log4cplus::ConsoleAppender(OFTrue /* logToStdErr */, OFTrue /* immediateFlush */));
    console->setLayout(OFmove(layout));
    dcmtk::log4cplus::Logger log = dcmtk::log4cplus::Logger::getRoot();
    log.removeAllAppenders();
    log.addAppender(console);
    log.setLogLevel(OFLogger::DEBUG_LOG_LEVEL);
}


// Test case that checks server scp tls connection
OFTEST_FLAGS(dcmtls_scp_tls, EF_None)
{
    /// Write key and cert files
    write_temp_key_cert_files();

    /// Init logs
    initLogs();

    /// Init scp tls layer
    OFCondition result;
    DcmTLSTransportLayer scpTlsLayer(NET_ACCEPTOR, NULL, OFTrue);
    result = scpTlsLayer.setPrivateKeyFile(PRIVATE_KEY_FILENAME, DCF_Filetype_PEM);
    OFCHECK(result.good());
    result = scpTlsLayer.setCertificateFile(PUBLIC_SELFSIGNED_CERT_FILENAME, DCF_Filetype_PEM, TSP_Profile_BCP_195_RFC_8996);
    OFCHECK(result.good());
    OFCHECK(scpTlsLayer.checkPrivateKeyMatchesCertificate());
    scpTlsLayer.setCertificateVerification(DCV_ignoreCertificate);

    /// Init and run Scp server with tls
    OFRandom rnd;
    TestSCP scp;
    DcmSCPConfig& config = scp.getConfig();
    config.setAETitle("ACCEPTOR");
    config.setACSETimeout(30);
    config.setConnectionTimeout(1);
    config.setMaxReceivePDULength(16856);
    config.setHostLookupEnabled(false);
    config.setConnectionBlockingMode(DUL_NOBLOCK);
    config.setRespondWithCalledAETitle("REQUESTOR");
    OFList<OFString> xfers;
    xfers.push_back(UID_LittleEndianImplicitTransferSyntax);
    OFCHECK(config.addPresentationContext(UID_VerificationSOPClass, xfers, ASC_SC_ROLE_SCP).good());

    config.setTransportLayer(&scpTlsLayer);

    // Ensure server is up and listening
    int i = 0;
    Uint16 port_number = 0;
    OFMutex memory_barrier;
    do
    {
      // generate a random port number between 61440 (0xF000) and 65535
      port_number = 0xF000 + (rnd.getRND16() & 0xFFF);
      config.setPort(port_number);
      scp.start();
      OFStandard::forceSleep(2); // wait 2 seconds for the SCP process to start
      memory_barrier.lock();
      memory_barrier.unlock();
    }
    while ((i++ < 5) && (! scp.m_is_running)); // try up to 5 port numbers before giving up

    if (! scp.m_is_running) BAILOUT("Start of the SCP thread failed: " << scp.m_listen_result.text());

    // Configure SCU and run it against SCP
    DcmTLSSCU scu;
    scu.setMaxReceivePDULength(16856);
    scu.setDIMSEBlockingMode(DIMSE_NONBLOCKING);
    scu.setDIMSETimeout(300);
    scu.setACSETimeout(30);
    scu.setPeerAETitle("ACCEPTOR");
    scu.setAETitle("REQUESTOR");
    scu.setPeerHostName("localhost");
    scu.setPeerPort(port_number);

    scu.enableAuthentication(PRIVATE_KEY_FILENAME, PUBLIC_SELFSIGNED_CERT_FILENAME, NULL /* key is unencrypted */, DCF_Filetype_PEM, DCF_Filetype_PEM);
    scu.setPeerCertVerification(DCV_ignoreCertificate);

    OFCHECK(scu.addPresentationContext(UID_VerificationSOPClass, xfers, ASC_SC_ROLE_SCU).good());

    OFCHECK(scu.initNetwork().good());
    OFCHECK(scu.negotiateAssociation().good());

    scp.m_set_stop_after_assoc = OFTrue;
    scp.m_set_stop_after_timeout = OFTrue;
    if (scu.isConnected())
        OFCHECK(scu.releaseAssociation().good());
    scp.join();
}


// Test case that checks server scp tls connection
OFTEST_FLAGS(dcmtls_scp_pool_tls, EF_None)
{
    /// Write key and cert files
    write_temp_key_cert_files();

    /// Init logs
    initLogs();

    /// Init scp tls layer
    OFCondition result;
    DcmTLSTransportLayer scpTlsLayer(NET_ACCEPTOR, NULL, OFTrue);
    result = scpTlsLayer.setPrivateKeyFile(PRIVATE_KEY_FILENAME, DCF_Filetype_PEM);
    OFCHECK(result.good());
    result = scpTlsLayer.setCertificateFile(PUBLIC_SELFSIGNED_CERT_FILENAME, DCF_Filetype_PEM, TSP_Profile_BCP_195_RFC_8996);
    OFCHECK(result.good());
    OFCHECK(scpTlsLayer.checkPrivateKeyMatchesCertificate());
    scpTlsLayer.setCertificateVerification(DCV_ignoreCertificate);

    /// Init and run Scp server with tls
    OFRandom rnd;
    TestPool pool;
    DcmSCPConfig& config = pool.getConfig();
    config.setAETitle("ACCEPTOR");
    config.setACSETimeout(30);
    config.setConnectionTimeout(1);
    config.setMaxReceivePDULength(16856);
    config.setHostLookupEnabled(false);
    config.setConnectionBlockingMode(DUL_NOBLOCK);
    config.setRespondWithCalledAETitle("REQUESTOR");
    OFList<OFString> xfers;
    xfers.push_back(UID_LittleEndianImplicitTransferSyntax);
    OFCHECK(config.addPresentationContext(UID_VerificationSOPClass, xfers, ASC_SC_ROLE_DEFAULT).good());
    config.setTransportLayer(&scpTlsLayer);
    pool.setMaxThreads(NUM_THREADS);

    // Ensure server is up and listening
    int i = 0;
    Uint16 port_number = 0;
    do
    {
      // generate a random port number between 61440 (0xF000) and 65535
      port_number = 0xF000 + (rnd.getRND16() & 0xFFF);
      config.setPort(port_number);
      pool.start();
      OFStandard::forceSleep(2); // wait 2 seconds for the SCP process to start
    }
    while ((i++ < 5) && (! pool.m_is_running)); // try up to 5 port numbers before giving up
    if (! pool.m_is_running) BAILOUT("Start of the SCP thread pool failed: " << pool.m_listen_result.text());

    OFVector<TestTLSSCU*> scus(NUM_THREADS);
    OFVector<DcmTLSTransportLayer*> scuTlsLayers;
    for (OFVector<TestTLSSCU*>::iterator it1 = scus.begin(); it1 != scus.end(); ++it1)
    {
        *it1 = new TestTLSSCU;
        (*it1)->setMaxReceivePDULength(16856);
        (*it1)->setDIMSEBlockingMode(DIMSE_NONBLOCKING);
        (*it1)->setDIMSETimeout(300);
        (*it1)->setACSETimeout(30);
        (*it1)->setPeerAETitle("ACCEPTOR");
        (*it1)->setAETitle("REQUESTOR");
        (*it1)->setPeerHostName("localhost");
        (*it1)->setPeerPort(port_number);
        (*it1)->enableAuthentication(PRIVATE_KEY_FILENAME, PUBLIC_SELFSIGNED_CERT_FILENAME, NULL /* key is unencrypted */, DCF_Filetype_PEM, DCF_Filetype_PEM);
        (*it1)->setPeerCertVerification(DCV_ignoreCertificate);

        OFList<OFString> ts;
        ts.push_back(UID_LittleEndianImplicitTransferSyntax);
        OFCHECK((*it1)->addPresentationContext(UID_VerificationSOPClass, ts, ASC_SC_ROLE_SCU).good());
        (*it1)->initNetwork();
    }

    // "ensure" the pool is initialized before any SCU starts connecting to it. The initialization
    // can take a couple of seconds on older systems, e.g. debian i368.
    OFStandard::forceSleep(5);

    for (OFVector<TestTLSSCU*>::const_iterator it2 = scus.begin(); it2 != scus.end(); ++it2)
    {
        (*it2)->start();
    }

    for (OFVector<TestTLSSCU*>::iterator it3 = scus.begin(); it3 != scus.end(); ++it3)
    {
        (*it3)->join();
        OFCHECK((*it3)->result.good());
        delete *it3;
    }

    for (OFVector<DcmTLSTransportLayer*>::iterator it4 = scuTlsLayers.begin(); it4 != scuTlsLayers.end(); ++it4)
    {
        delete *it4;
    }

    pool.stopAfterCurrentAssociations();
    pool.join();
}

#endif // WITH_OPENSSL

#endif // WITH_THREADS

#if (!defined(WITH_THREADS)) || (!defined(WITH_OPENSSL))

// Dummy versions of the test cases. Needed to prevent ctest test failures.
OFTEST(dcmtls_scp_tls)
{
}

OFTEST(dcmtls_scp_pool_tls)
{
}

// This dummy function creates a dependency on libdcmnet that is required when compiling
// on NetBSD with libwrap support enabled and OpenSSL support disabled. Otherwise there
// would be a linker error complaining about unresolved symbols allow_severity and deny_severity.

DcmTransportLayer *tscuscptls_dummyFunction()
{
  return new DcmTransportLayer();
}

#endif
