/*
 *
 *  Copyright (C) 2019-2026, OFFIS e.V.
 *  All rights reserved.  See COPYRIGHT file for details.
 *
 *  This software and supporting documentation were developed by
 *
 *    OFFIS e.V.
 *    R&D Division Health
 *    Escherweg 2
 *    D-26121 Oldenburg, Germany
 *
 *
 *  Module:  dcmtls
 *
 *  Authors:  Michel Amat, Damien Lerat, Michael Onken
 *
 *  Purpose: TLS test for classes DcmSCP and DcmSCPPool
 *
 *  Note: This test will fail after 2029-02-25 due to certificate expiry.
 *        The keys embedded in this file should be replaced then (see below).
 *
 *  Note: The embedded private key is encrypted with AES-256-CBC. Do not use
 *        3DES (des-ede3-cbc, the historic OpenSSL default), because on some
 *        modern OpenSSL builds (e.g. Debian trixie) 3DES is not available in
 *        the default provider, which makes loading the key fail with a
 *        "DECODER routines::unsupported" error and breaks the TLS handshake.
 *
 */

#include "dcmtk/config/osconfig.h"    /* make sure OS specific configuration is included first */

#include "dcmtk/ofstd/oftest.h"
#include "dcmtk/ofstd/oftimer.h"
#include "dcmtk/ofstd/ofrand.h"
#include "dcmtk/oflog/consap.h"
#include "dcmtk/dcmnet/scp.h"
#include "dcmtk/dcmnet/scu.h"
#include "dcmtk/dcmnet/scppool.h"
#include "dcmtk/dcmnet/dcmlayer.h"
#include "dcmtk/dcmtls/tlsscu.h"
#include <cmath>

#ifdef WITH_THREADS
#ifdef WITH_OPENSSL

#define BAILOUT(msg) do { \
    OFCHECK_FAIL(msg); \
    return; \
} while (0)

const size_t NUM_THREADS = 20;

/** TestSCP derived from DcmSCP in order to test TLS functionality
 *  through function setTransportLayer of DcmSCPConfig.
 *
 *  Additionally the SCP derives from OFThread in order to construct the
 *  test case (i.e. send data with SCU at the same time and check results).
 */
struct TestSCP: DcmSCP, OFThread
{
    /** Constructor
     */
    TestSCP() :
        DcmSCP(),
        m_listen_result(EC_NotYetImplemented), // value indicating "not set"
        m_set_stop_after_assoc(OFFalse),
        m_set_stop_after_timeout(OFFalse),
        m_is_running(OFFalse)
    {
    }

    /** Clear settings
     */
    void clear()
    {
        m_listen_result = EC_NotYetImplemented;
        m_set_stop_after_assoc = OFFalse;
        m_set_stop_after_timeout = OFFalse;
        m_is_running = OFFalse;
    }

    /** Overwrite method from DcmSCP in order to test feature to stop after current
     *  association.
     *  @return Returns value of m_set_stop_after_assoc
     */
    virtual OFBool stopAfterCurrentAssociation()
    {
        return m_set_stop_after_assoc;
    }

    /** Overwrite method from DcmSCP in order to test feature to stop after
    *   the SCP's connection timeout occurred in non-blocking mode.
    *   @return Returns value of m_set_stop_after_timeout
    */
    virtual OFBool stopAfterConnectionTimeout()
    {
        return m_set_stop_after_timeout;
    }

    /// The result returned my SCP's listen() method
    OFCondition m_listen_result;
    /// If set, the SCP should stop after the currently running association
    OFBool m_set_stop_after_assoc;
    /// If set, the SCP should stop after TCP timeout occurred in non-blocking mode
    OFBool m_set_stop_after_timeout;
    /// indicates whether the thread is currently running
    volatile OFBool m_is_running;

    /** Method called by OFThread to start SCP operation. Starts listen() loop of DcmSCP.
    */
    virtual void run()
    {
        m_is_running = OFTrue;
        m_listen_result = listen();
        m_is_running = OFFalse;
    }

};

// -------------- End of class TestSCP -------------------------

struct TestPool : DcmSCPPool<>, OFThread
{
    OFCondition m_listen_result;
    volatile OFBool m_is_running;

    TestPool()
    : DcmSCPPool<>()
    , OFThread()
    , m_listen_result(EC_NotYetImplemented)
    , m_is_running(OFFalse)
    { }

protected:
    void run()
    {
        m_is_running = OFTrue;
        m_listen_result = listen();
        m_is_running = OFFalse;
        DCMNET_DEBUG("TestPool: SCP Pool thread stopped, listen() returned: " << m_listen_result.text());
    }
};

// -------------- End of class TestPool -------------------------

struct TestTLSSCU : DcmTLSSCU, OFThread
{
    OFCondition result;
protected:
    void run()
    {
        OFCHECK(negotiateAssociation().good());
        result = sendECHORequest(0);
        releaseAssociation();
    }
};

// -------------- End of class TestTLSSCU -------------------------


#define PRIVATE_KEY_FILENAME "privkey.pem"
#define PUBLIC_SELFSIGNED_CERT_FILENAME "pubselfsignedcert.pem"
#define PRIVATE_KEY_PWD "testDcmtk!"


/** Method write_temp_key_cert_files writes private key and public certificate files,
 *  needed by tests dcmtls_scp_tls and dcmtls_scp_pool_tls.
 *  It corresponds to the files generated by the following openssl command>
 *  > openssl req -x509 -newkey rsa:4096 -keyout PRIVATE_KEY_FILENAME  -passout pass:PRIVATE_KEY_PWD
 *    -out PUBLIC_SELFSIGNED_CERT_FILENAME -days 3653 -subj "/C=DE/ST=DcmTls/L=Tests/O=OFFIS/OU=DCMTK/CN=dicom@offis.de"
 *  The private key was subsequently re-encrypted with AES-256-CBC (the certificate is unchanged):
 *  > openssl pkcs8 -topk8 -v2 aes-256-cbc -in PRIVATE_KEY_FILENAME -passin pass:PRIVATE_KEY_PWD -passout pass:PRIVATE_KEY_PWD
 *  @note The certificate will expire on 2029-02-25. The keys should be replaced then.
 */
void write_temp_key_cert_files()
{
    const char * privKey="-----BEGIN ENCRYPTED PRIVATE KEY-----\n"
"MIIJtTBfBgkqhkiG9w0BBQ0wUjAxBgkqhkiG9w0BBQwwJAQQjVVDgUHHAGAvqu7d\n"
"OV8AtAICCAAwDAYIKoZIhvcNAgkFADAdBglghkgBZQMEASoEELSUHgs0iYtZvA8B\n"
"yO3tg5sEgglQN1Il9IHxmVeN+z2OrDRlH3I3D9K8VpOo4fZwWgbg9ULmm63jXOGl\n"
"5dhYFRXzB/LiIFyUoTteUdE1VPlDoCobXHwlmGWLBP0DA31dkpBg3Q1Aaq9a4YQ+\n"
"DLxd9S3Oo1wS+tYewc42g1+LESdh5zFvD41kUW0eZvF9N4CEPpprzkBtuSLy5I9G\n"
"K2Ki2BWByBbnZdVPpAPm1qkGMXX5XXOGVPdoyUrK+xGgOmlJnhoc7u5/n11x4YZV\n"
"OT5XLSO5RCbx1a/QgmNWV9AmYN9I0Ign3KvGo5Dg4E+qwMgt2Am9DeDkTtcpBBcx\n"
"khoCz5Ge8PLkpPis1d1flUh/A9twVGf8+lZThz149kgXhcM6QnbpFodf0fysTpTI\n"
"q+vNX6GblJcC9BTatSL+IllaL913VcTz+tXp9jwTAF8VGRwzdhk4OhlvG1aoW/Ey\n"
"LI1tE5z9Tnk5yq3FomrmeRAGwxWzPtDrlYSo6PIDhhJicpgA8aBBoegMxlL7ItKP\n"
"ZtxD71rNpEVAITii+wuBnLTXyYOePxKrwAzNOWleUr7qJSQ/yrOrjr3ymhHajXSk\n"
"UuqWOYfn9jUXCrodQmzjDRmgXZhHwoUGs8mZU+BuXkx4aZ+VfklvkwUzCusvR6wu\n"
"U8FULxDe5QyEDXzLfKJj9MQk7JUugmSLq/912rPLyUdMTJPgQOQsbM/ABjqmAlxI\n"
"vOMHu3XncnODoqWSSKcKizsBNEIBrI48/BC52DmKyX6XspMYWjfRG1jDYjBJ9TYQ\n"
"nQQ7JLw9Y0PpUfflWpSg7cFa7VaFuMpJ5XjxVYC6cj5vTarLWqnvvyV9A5AxE9A3\n"
"pPyVRttrtkJ4AKKjAAjPSuaPoGCHRCaODad27TaS3hbJDapmd+w6iCSFeFua7AbR\n"
"qqp2V6sz9HtEr4zLOIq9X3YrdPdJBDtlGH17ZBrHmEwT9rcWsHHPGpJ/0PFdsje8\n"
"zIDiELymYu3PoYpWwup6in8tiQ3faPAp1No3C/v2OxNxgUeJ0kTAg5hOw7d3JYZK\n"
"dDDwit/cDyDCmOM7adkn443CUlJ0CNGaICYpO+NSjYVNZUzASwU7g9RjdGfNNrl+\n"
"XGUbrCnY1CwSgQ6rLz5kqAOvcKn+d6MxIOED4ZqcN6WYh2qN5rdd/neVlwrQ8lJB\n"
"AyQMcf4LpAcpoQdey7bo39RoefYO8iunIp04ypLlPE8F99BFlZd466Pw/iqdJ8CT\n"
"TAiL1Dm+UdFqtzbyYD2J0s8szCH2hwhLoTe7KLC5FeQTESvdGStQHDVNr01Ps7nL\n"
"hS1mOJzV2s7jpVdoA/cI4s9c0urv4I4zxpmg1AGYHBL6uhLLq0FA1jF/+yfyotbs\n"
"XtXYQSNDNZlaU3+5bxnghZ1kvMai5JktvrSFIP0+0VZZh5Sq5jdreJpIiLQmZ8ED\n"
"iaWT/N19we766P1f8IfaeLD1f9Y+Ypspxj4kRgYpax/r/hBMusxCey1e2ZeGqcM1\n"
"zvCl8ZUIkyQJCP11RPAOqB6D/lNhFIP3LjRDQpZY/ichw545QBycjIEFJJJg5F50\n"
"8Xax3VQP92YS8DMuEviQPpAvOyl530FWt24c3GZOY0m7A7QoanrP/8Ipd72MuFWs\n"
"+eTmcwvV648Jk19Et+1tFqtWY1KnFGsn/7mnoIUlC1/8XL2P6rijBY2zjMn9G8ny\n"
"+CzN698T9/oXdsRnACG9I0Z7EMMcl1X1sSny2d/S/7T8eX+XCYpdqXSDlxNcF03g\n"
"1W8mSev/wafDFJCimKe+vhaCEJ/fobtnzplmnSupxlkuMDOuuBCYehKqbOWYRm1k\n"
"8EuTknUJxdfZPz8FndVH/Jy6w/yEzmQm23lgVSPiBQD/8OdRwXXeDBkROfAZuf34\n"
"sZowFo0qY7aO3Q7dZNB3umAJluoTTiQUM/VIhH7MjuuF154TCUKiYVMxNYVjr2O0\n"
"qHpyBkHXPGyjl11h+UT3Qt2lX0xHNxU6K5glLTQck+utYjtgmo/FWngBMA2MngM3\n"
"8eZ5VHw3eM23aC1NZJud2qdrZBdq3K7MxAjwdZRNQN9miB+774vsGf4zdGUO4CJy\n"
"nLW0GkC7spnqUeUgQ0qWQSh+x56MNndvnmAm+9b1WvVIi9+TUbUcTjUOgFVl8Fe/\n"
"iwk4mK1hFB4ussdMV0gwwFwLQDYwtaOXfgPKgEayuw6rd/OFyrQcwSi54rrE5XTv\n"
"6mmIdCpcoaFy3MHoM8bjCbHcu+ulYbZOHRqZXlPlc4JnpXfQ0K2NLYTeLyWvw3si\n"
"ttnOv/v64zkYdBEgSfg1ImV3R2TsnVqu8j65rancqdNjRO9cfMUtw0UTsnTT/gjy\n"
"Olv7ny8HTdc96vXzrTP5k1YfJAAIdtQy2d0KV9Meep1IyvUi91G/GXjoYFyJhobG\n"
"adBW73igEPXzPNTdHhFC7xmUYuH3O5QQFVmhn4RmwMMoWzo7NS9B7XqZNi3NH17a\n"
"Nc4xv93fbFF3OrC/osOo1hgNf1jSYtawIRXM+4XhBqy5wwindoevHixrGmaJb/1M\n"
"iUXkeVMApC7MoAftNyHPOnMXa3iRjABiiSyfPtggpraesXZNhJkQdUHMtylm3W9v\n"
"CQvmW+mnV5kqf0zvZhUPPf0Vu2ciumbE2MUx+h01aYsL5yhJVzTsnpkQrhehcOGk\n"
"xiVhgw/H3BmL0n/ZYVeISClVMBXdLF0HgcW24ZKPFlXFH2a8oIK7lKMzVe7b3ZwX\n"
"J6tGcBO34ED5bO+JN1niLz6i5lSnD+XVGTkATUyfT1DeIUtvJuJXzCAjpG12kqE+\n"
"ddgAWkyYjlAP2yf47ToD/joOEUxPREjmG0bFW+ZXvgBdTDn6nWlIu7ulbH+uqvMN\n"
"pZl1GiNZ1oIv4d08NrJphHbE3+KUQYorc/VrHaxU7D5Gd82Cvoe7PUMVbVd8DrtV\n"
"lx9Cz6nxWB09lr/cqA92B0t51+7dKDfVFFBefQ3HjMzrNQzK66fNPN8OuVuwyw0h\n"
"IiD6WO5yU0DEN8wCJr7Cxi3KbuOdvUd2uXSPhzs4oHiEzjAge6Z39Yh13EWbTFmX\n"
"K3DHxSkJjG5siO/4qh9x9jD5O1r7xaX6e2MdZungtIUD13Jhnmzmi8iMWuvKFvy9\n"
"iUXkzpNvPVREgtIS7kef7iLC8fJR7wolKx0nF8ADbfOgq1B4IPfrjMP7XzVjGejQ\n"
"aj8N6lAAMK3IV40rE/dDpHW7R79rZUYlRkUi4ugzeuJfZu3NeFhVuMs=\n"
"-----END ENCRYPTED PRIVATE KEY-----";
    const size_t lenPrivKey = 3445;
    FILE *privKeyFile = fopen(PRIVATE_KEY_FILENAME, "wb");
    OFCHECK(privKeyFile);
    OFCHECK(lenPrivKey == fwrite(privKey, 1, lenPrivKey, privKeyFile));
    fclose(privKeyFile);

    const char* pubSelfSIgnedCert =
    "-----BEGIN CERTIFICATE-----\n"
"MIIFpDCCA4ygAwIBAgIJAJRhU6soYQspMA0GCSqGSIb3DQEBCwUAMGcxCzAJBgNV\n"
"BAYTAkRFMQ8wDQYDVQQIDAZEY21UbHMxDjAMBgNVBAcMBVRlc3RzMQ4wDAYDVQQK\n"
"DAVPRkZJUzEOMAwGA1UECwwFRENNVEsxFzAVBgNVBAMMDmRpY29tQG9mZmlzLmRl\n"
"MB4XDTE5MDIyNTE0MjY0NVoXDTI5MDIyNTE0MjY0NVowZzELMAkGA1UEBhMCREUx\n"
"DzANBgNVBAgMBkRjbVRsczEOMAwGA1UEBwwFVGVzdHMxDjAMBgNVBAoMBU9GRklT\n"
"MQ4wDAYDVQQLDAVEQ01USzEXMBUGA1UEAwwOZGljb21Ab2ZmaXMuZGUwggIiMA0G\n"
"CSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQC+YYUnYLhLIuhizqUUO4KtzaKmqJ4z\n"
"Y5mn9H9J0U721C932F702CX38KhZOMRc/7C0cNxdYWDFS7iEjl90kwNmfkdVK8Xj\n"
"dLQ6GVTjvkVI6caeQBe3MgSvVRtczmhMqgP8DoNFSP7/OUTTcTcoHquoVIrViCOH\n"
"8vc/6mfBFA5qsoGDwi3A/LgUh/mNHqAZqAkomEzmHihNrM9RA8a+7doqjNf7IrQU\n"
"Hx7ubK+RozprXvqMTKGddy+gbbmFzCyWLgDC2ak25p1qMNVqDlZYhrfV+Q0M7fQG\n"
"OJw97SLjyHXT9P93IWO+WbLCdSmj/GBIx/nLMzRSVUbPPvUm37uhy2mSfgIhE8w8\n"
"ybVnXRLJdxUyHwpZVm+UktCPv/IU8LdgxA1sKx7+S/7BgwIS0rXX3O3yeB1z/dFS\n"
"kT44Ju+Ze8MAPxVoyWbF+SaKmy9LcsRpjjIusJLTDT3W1Pw+AymYDt0BKq5rDnd4\n"
"gx/dKuRd/921GFAnrZE86rmWbvTuqYGCYeaJfRnhCDmjWLgq/jlrc37fTv2TJXF7\n"
"TGNjkfGsjS1StC9IOnGXyhV0klvK5xxPvIGVHUbVi2bXDW9HUTmtZ6O0vFM7NgRh\n"
"UimndmrLbEJJGNGG36h5kIMe5xo7C99utu+d077itL4ZPcOyeeEHXaObjxQEzQ8x\n"
"RnkDOWzIDTU9ZQIDAQABo1MwUTAdBgNVHQ4EFgQU84HK6/XZJXpkS53bNQSma5YR\n"
"QIUwHwYDVR0jBBgwFoAU84HK6/XZJXpkS53bNQSma5YRQIUwDwYDVR0TAQH/BAUw\n"
"AwEB/zANBgkqhkiG9w0BAQsFAAOCAgEAdNRVhkbUS77PlG6TvwYBhRwijy0F3rUX\n"
"BVs4MidSaK8V9Cxa/m018GV0xoz52zIibLUiKLvRUNo3qS24Gbfbh9fdKoIBaTpG\n"
"ike3lS19ddovqQE6WsTTQWjbVP5+B4BVvGbqJNBUFI1vn8dxHFCmWDWqQJy44PqF\n"
"bp88vegFc51dTsrWVWfvTVUP56vmINm2EnvCHEJjQXp7AODlvanC358oJ18YWHzX\n"
"WgGqTE7J4Eab9lmRWMb+ArHvVqwXm5aIFAl/JJ3faJIgW1pqGyKnlQYeiQOOy+YG\n"
"pXCqUxiTMyWP27hoCMG5v3IXdbmIXedD6CwAV0yq6uZUz62g23rXaJiG0wILWMP0\n"
"xzPGnBJHz7VmXMPX1Fs8AxgHZn41N1LCT1BmnFMPmTQb4v/eHSihYHVORkvhdwQu\n"
"LJxKz8oawnka6n9UXF+rVdJjXCeYEA5Y9ThW6Qio3vjrFR5vX70EuVlu/bXqSg3J\n"
"tw+7Gn0C1XfjBtnRJPcSKdBhrkooB2Kl6nkgxy1yTyOXvG1xLeJgJw6/MiCuFu5g\n"
"DZRABWjQPrqv8rFyYm7jwa8sTAppmANazi6SsUGC27cXICVGw3zP7FrXI3jerMkv\n"
"LN+tQ/fnbPFx0kM8PW8Fx6/ns51MMzDZkCdD8yM/Bg74culg20rr25MAa/L0VGq8\n"
"x+yqEeQzzYQ=\n"
"-----END CERTIFICATE-----";
    const size_t lenPubSelfSignedCert = 2016;
    FILE *pubSelfSignedCertFile = fopen(PUBLIC_SELFSIGNED_CERT_FILENAME, "wb");
    OFCHECK(pubSelfSignedCertFile);
    OFCHECK(lenPubSelfSignedCert == fwrite(pubSelfSIgnedCert, 1, lenPubSelfSignedCert, pubSelfSignedCertFile));
    fclose(pubSelfSignedCertFile);
}

// Function for initialization of logs with console appender
void initLogs()
{
    const char * const LOG_PATTERN_LAYOUT = "%D{%Y-%m-%d %H:%M:%S.%q} %5p: %m%n";
    OFunique_ptr < dcmtk::log4cplus::Layout > layout(new dcmtk::log4cplus::PatternLayout(LOG_PATTERN_LAYOUT));
    dcmtk::log4cplus::SharedAppenderPtr console(new dcmtk::log4cplus::ConsoleAppender(OFTrue /* logToStdErr */, OFTrue /* immediateFlush */));
    console->setLayout(OFmove(layout));
    dcmtk::log4cplus::Logger log = dcmtk::log4cplus::Logger::getRoot();
    log.removeAllAppenders();
    log.addAppender(console);
    log.setLogLevel(OFLogger::DEBUG_LOG_LEVEL);
}


// Test case that checks server scp tls connection
OFTEST_FLAGS(dcmtls_scp_tls, EF_None)
{
    /// Write key and cert files
    write_temp_key_cert_files();

    /// Init logs
    initLogs();

    /// Init scp tls layer
    OFCondition result;
    DcmTLSTransportLayer scpTlsLayer(NET_ACCEPTOR, NULL, OFTrue);
    scpTlsLayer.setPrivateKeyPasswd(PRIVATE_KEY_PWD);
    result = scpTlsLayer.setPrivateKeyFile(PRIVATE_KEY_FILENAME, DCF_Filetype_PEM);
    OFCHECK(result.good());
    result = scpTlsLayer.setCertificateFile(PUBLIC_SELFSIGNED_CERT_FILENAME, DCF_Filetype_PEM, TSP_Profile_BCP_195_RFC_8996);
    OFCHECK(result.good());
    OFCHECK(scpTlsLayer.checkPrivateKeyMatchesCertificate());
    scpTlsLayer.setCertificateVerification(DCV_ignoreCertificate);

    /// Init and run Scp server with tls
    OFRandom rnd;
    TestSCP scp;
    DcmSCPConfig& config = scp.getConfig();
    config.setAETitle("ACCEPTOR");
    config.setACSETimeout(30);
    config.setConnectionTimeout(1);
    config.setMaxReceivePDULength(16856);
    config.setHostLookupEnabled(false);
    config.setConnectionBlockingMode(DUL_NOBLOCK);
    config.setRespondWithCalledAETitle("REQUESTOR");
    OFList<OFString> xfers;
    xfers.push_back(UID_LittleEndianImplicitTransferSyntax);
    OFCHECK(config.addPresentationContext(UID_VerificationSOPClass, xfers, ASC_SC_ROLE_SCP).good());

    config.setTransportLayer(&scpTlsLayer);

    // Ensure server is up and listening
    int i = 0;
    Uint16 port_number = 0;
    OFMutex memory_barrier;
    do
    {
      // generate a random port number between 61440 (0xF000) and 65535
      port_number = 0xF000 + (rnd.getRND16() & 0xFFF);
      config.setPort(port_number);
      scp.start();
      OFStandard::forceSleep(2); // wait 2 seconds for the SCP process to start
      memory_barrier.lock();
      memory_barrier.unlock();
    }
    while ((i++ < 5) && (! scp.m_is_running)); // try up to 5 port numbers before giving up

    if (! scp.m_is_running) BAILOUT("Start of the SCP thread failed: " << scp.m_listen_result.text());

    // Configure SCU and run it against SCP
    DcmTLSSCU scu;
    scu.setMaxReceivePDULength(16856);
    scu.setDIMSEBlockingMode(DIMSE_NONBLOCKING);
    scu.setDIMSETimeout(300);
    scu.setACSETimeout(30);
    scu.setPeerAETitle("ACCEPTOR");
    scu.setAETitle("REQUESTOR");
    scu.setPeerHostName("localhost");
    scu.setPeerPort(port_number);

    scu.enableAuthentication(PRIVATE_KEY_FILENAME, PUBLIC_SELFSIGNED_CERT_FILENAME, PRIVATE_KEY_PWD, DCF_Filetype_PEM, DCF_Filetype_PEM);
    scu.setPeerCertVerification(DCV_ignoreCertificate);

    OFCHECK(scu.addPresentationContext(UID_VerificationSOPClass, xfers, ASC_SC_ROLE_SCU).good());

    OFCHECK(scu.initNetwork().good());
    OFCHECK(scu.negotiateAssociation().good());

    scp.m_set_stop_after_assoc = OFTrue;
    scp.m_set_stop_after_timeout = OFTrue;
    if (scu.isConnected())
        OFCHECK(scu.releaseAssociation().good());
    scp.join();
}


// Test case that checks server scp tls connection
OFTEST_FLAGS(dcmtls_scp_pool_tls, EF_None)
{
    /// Write key and cert files
    write_temp_key_cert_files();

    /// Init logs
    initLogs();

    /// Init scp tls layer
    OFCondition result;
    DcmTLSTransportLayer scpTlsLayer(NET_ACCEPTOR, NULL, OFTrue);
    scpTlsLayer.setPrivateKeyPasswd(PRIVATE_KEY_PWD);
    result = scpTlsLayer.setPrivateKeyFile(PRIVATE_KEY_FILENAME, DCF_Filetype_PEM);
    OFCHECK(result.good());
    result = scpTlsLayer.setCertificateFile(PUBLIC_SELFSIGNED_CERT_FILENAME, DCF_Filetype_PEM, TSP_Profile_BCP_195_RFC_8996);
    OFCHECK(result.good());
    OFCHECK(scpTlsLayer.checkPrivateKeyMatchesCertificate());
    scpTlsLayer.setCertificateVerification(DCV_ignoreCertificate);

    /// Init and run Scp server with tls
    OFRandom rnd;
    TestPool pool;
    DcmSCPConfig& config = pool.getConfig();
    config.setAETitle("ACCEPTOR");
    config.setACSETimeout(30);
    config.setConnectionTimeout(1);
    config.setMaxReceivePDULength(16856);
    config.setHostLookupEnabled(false);
    config.setConnectionBlockingMode(DUL_NOBLOCK);
    config.setRespondWithCalledAETitle("REQUESTOR");
    OFList<OFString> xfers;
    xfers.push_back(UID_LittleEndianImplicitTransferSyntax);
    OFCHECK(config.addPresentationContext(UID_VerificationSOPClass, xfers, ASC_SC_ROLE_DEFAULT).good());
    config.setTransportLayer(&scpTlsLayer);
    pool.setMaxThreads(NUM_THREADS);

    // Ensure server is up and listening
    int i = 0;
    Uint16 port_number = 0;
    do
    {
      // generate a random port number between 61440 (0xF000) and 65535
      port_number = 0xF000 + (rnd.getRND16() & 0xFFF);
      config.setPort(port_number);
      pool.start();
      OFStandard::forceSleep(2); // wait 2 seconds for the SCP process to start
    }
    while ((i++ < 5) && (! pool.m_is_running)); // try up to 5 port numbers before giving up
    if (! pool.m_is_running) BAILOUT("Start of the SCP thread pool failed: " << pool.m_listen_result.text());

    OFVector<TestTLSSCU*> scus(NUM_THREADS);
    OFVector<DcmTLSTransportLayer*> scuTlsLayers;
    for (OFVector<TestTLSSCU*>::iterator it1 = scus.begin(); it1 != scus.end(); ++it1)
    {
        *it1 = new TestTLSSCU;
        (*it1)->setMaxReceivePDULength(16856);
        (*it1)->setDIMSEBlockingMode(DIMSE_NONBLOCKING);
        (*it1)->setDIMSETimeout(300);
        (*it1)->setACSETimeout(30);
        (*it1)->setPeerAETitle("ACCEPTOR");
        (*it1)->setAETitle("REQUESTOR");
        (*it1)->setPeerHostName("localhost");
        (*it1)->setPeerPort(port_number);
        (*it1)->enableAuthentication(PRIVATE_KEY_FILENAME, PUBLIC_SELFSIGNED_CERT_FILENAME, PRIVATE_KEY_PWD, DCF_Filetype_PEM, DCF_Filetype_PEM);
        (*it1)->setPeerCertVerification(DCV_ignoreCertificate);

        OFList<OFString> ts;
        ts.push_back(UID_LittleEndianImplicitTransferSyntax);
        OFCHECK((*it1)->addPresentationContext(UID_VerificationSOPClass, ts, ASC_SC_ROLE_SCU).good());
        (*it1)->initNetwork();
    }

    // "ensure" the pool is initialized before any SCU starts connecting to it. The initialization
    // can take a couple of seconds on older systems, e.g. debian i368.
    OFStandard::forceSleep(5);

    for (OFVector<TestTLSSCU*>::const_iterator it2 = scus.begin(); it2 != scus.end(); ++it2)
    {
        (*it2)->start();
    }

    for (OFVector<TestTLSSCU*>::iterator it3 = scus.begin(); it3 != scus.end(); ++it3)
    {
        (*it3)->join();
        OFCHECK((*it3)->result.good());
        delete *it3;
    }

    for (OFVector<DcmTLSTransportLayer*>::iterator it4 = scuTlsLayers.begin(); it4 != scuTlsLayers.end(); ++it4)
    {
        delete *it4;
    }

    pool.stopAfterCurrentAssociations();
    pool.join();
}

#endif // WITH_OPENSSL

#endif // WITH_THREADS

#if (!defined(WITH_THREADS)) || (!defined(WITH_OPENSSL))

// Dummy versions of the test cases. Needed to prevent ctest test failures.
OFTEST(dcmtls_scp_tls)
{
}

OFTEST(dcmtls_scp_pool_tls)
{
}

// This dummy function creates a dependency on libdcmnet that is required when compiling
// on NetBSD with libwrap support enabled and OpenSSL support disabled. Otherwise there
// would be a linker error complaining about unresolved symbols allow_severity and deny_severity.

DcmTransportLayer *tscuscptls_dummyFunction()
{
  return new DcmTransportLayer();
}

#endif
